packages:
  - internals/website-examples
  - packages/*
  - apps/*
  - apps/vscode-extension/webview-ui
  - apps/vscode-extension/worker
  - apps/vscode-extension/interface
  - test
  - website
catalogs:
  agentica:
    '@agentica/core': ^0.34.0
    '@agentica/rpc': ^0.34.0
  samchon:
    '@nestia/benchmark': ^9.0.0
    '@nestia/core': ^9.0.0
    '@nestia/e2e': ^9.0.0
    '@nestia/editor': ^9.0.0
    '@nestia/fetcher': ^9.0.0
    '@nestia/migrate': ^9.0.0
    '@nestia/sdk': ^9.0.0
    '@samchon/openapi': ^5.0.0
    embed-eslint: ^2.0.1
    embed-prisma: ^1.1.2
    embed-typescript: ^2.0.1
    nestia: ^9.0.0
    prisma-markdown: ^3.0.0
    tgrid: ^1.2.0
    tstl: ^3.0.0
    typia: ^10.0.0
  typescript:
    '@typescript-eslint/eslint-plugin': 8.40.0
    '@typescript-eslint/parser': 8.40.0
    eslint: 9.34.0
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.3
  prisma:
    '@prisma/adapter-pg': ^6.16.2
    '@prisma/adapter-better-sqlite3': ^6.16.2
    '@prisma/client': ^6.16.2
    '@prisma/internals': ^6.16.2
    prisma: ^6.16.2
  ui:
    react: ^19.1.1
    react-dom: ^19.1.1
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.5
    vite: ^6.3.5
  libs:
    openai: ^6.7.0
useNodeVersion: 22.15.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
