packages:
  - internals/website-examples
  - packages/*
  - apps/*
  - apps/vscode-extension/webview-ui
  - apps/vscode-extension/worker
  - apps/vscode-extension/interface
  - test
  - website
catalogs:
  agentica:
    '@agentica/core': ^0.32.1
    '@agentica/rpc': ^0.32.1
  samchon:
    '@nestia/benchmark': ^7.3.3
    '@nestia/core': ^7.3.3
    '@nestia/e2e': ^7.3.3
    '@nestia/editor': ^7.3.3
    '@nestia/fetcher': ^7.3.3
    '@nestia/migrate': ^7.3.3
    '@nestia/sdk': ^7.3.3
    '@samchon/openapi': ^4.7.1
    embed-prisma: ^1.1.0
    embed-typescript: ^1.0.1
    prisma-markdown: ^3.0.0
    tgrid: ^1.2.0
    tstl: ^3.0.0
    typia: ^9.7.1
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.2
  ui:
    react: ^19.1.1
    react-dom: ^19.1.1
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.5
    vite: ^6.3.5
  libs:
    openai: ^5.12.2
useNodeVersion: 22.15.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
