packages:
  - internals/website-examples
  - packages/*
  - apps/*
  - apps/vscode-extension/webview-ui
  - apps/vscode-extension/worker
  - apps/vscode-extension/interface
  - test
  - website
catalogs:
  agentica:
    '@agentica/core': 0.32.3-dev.3
    '@agentica/rpc': 0.32.3-dev.3
  samchon:
    '@nestia/benchmark': ^8.0.1
    '@nestia/core': ^8.0.1
    '@nestia/e2e': ^8.0.1
    '@nestia/editor': ^8.0.1
    '@nestia/fetcher': ^8.0.1
    '@nestia/migrate': ^8.0.1
    '@nestia/sdk': ^8.0.1
    '@samchon/openapi': ^4.7.1
    embed-eslint: ^2.0.1
    embed-prisma: ^1.1.0
    embed-typescript: ^2.0.1
    nestia: ^8.0.1
    prisma-markdown: ^3.0.0
    tgrid: ^1.2.0
    tstl: ^3.0.0
    typia: ^9.7.2
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.2
  ui:
    react: ^19.1.1
    react-dom: ^19.1.1
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.5
    vite: ^6.3.5
  libs:
    openai: ^5.12.2
useNodeVersion: 22.15.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
