packages:
  - internals/website-examples
  - packages/*
  - apps/*
  - apps/vscode-extension/webview-ui
  - apps/vscode-extension/worker
  - apps/vscode-extension/interface
  - test
  - website
catalogs:
  agentica:
    '@agentica/core': ^0.39.0
  samchon:
    '@nestia/benchmark': ^10.0.2
    '@nestia/core': ^10.0.2
    '@nestia/e2e': ^10.0.2
    '@nestia/editor': ^10.0.2
    '@nestia/fetcher': ^10.0.2
    '@nestia/migrate': ^10.0.2
    '@nestia/sdk': ^10.0.2
    '@samchon/openapi': ^6.0.1
    embed-eslint: ^2.0.1
    embed-prisma: ^3.0.0
    embed-typescript: ^2.0.1
    nestia: ^10.0.2
    prisma-markdown: ^4.0.0
    tgrid: ^1.2.1
    tstl: ^3.0.0
    typia: ^11.0.2
  typescript:
    '@typescript-eslint/eslint-plugin': 8.40.0
    '@typescript-eslint/parser': 8.40.0
    eslint: 9.34.0
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.3
    typescript-transform-paths: ^3.5.5
  prisma:
    '@prisma/adapter-pg': ^7.0.0
    '@prisma/adapter-better-sqlite3': ^7.0.0
    '@prisma/client': ^7.0.0
    '@prisma/client-runtime-utils': ^7.0.0
    '@prisma/internals': ^7.0.0
    prisma: ^7.0.0
  ui:
    '@emotion/cache': ^11.14.0
    '@emotion/react': ^11.11.1
    '@emotion/styled': ^11.14.0
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.5
    react: ^19.1.1
    react-dom: ^19.1.1
    vite: ^6.3.5
  libs:
    openai: ^6.15.0
useNodeVersion: 22.15.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar