[default]
locale = 'en-us'
extend-ignore-re = [
  ".*(?:#|--|//|/*).*(?:spellchecker|typos):\\s?ignore[^\\n]*\\n",
  ".*(?:spellchecker|typos):\\s?ignore-next-line[^\\n]*\\n[^\\n]*",
  "(?s)(<!--|#|//)\\s*spellchecker:off\\s*(-->|\n).*?(<!--|#|//)\\s*spellchecker:on",
]

[default.extend-words]
typia = "typia"
criterias = "criterias"
Jeongho = "Jeongho"
Nam = "Nam"

[files]
extend-exclude = [
  "examples",
  "*.json", 
  "*.prisma",
  "test/assets/**",
]