name: build
on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'test/**'
      - 'test/package.json'
      - 'package.json'
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
      
      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Run Tests
        run: pnpm start
        working-directory: test

      - name: Run Hackathon Server Test
        run: |
          pnpm run schema
          pnpm run test --reset true
        working-directory: apps/hackathon-server